### ISSUE TITLE
Go prefers mixed caps instead of snake case

### ISSUE THREAD

**Issue by ejstembler** [BlazingFire007/gurl#1]
See [Effective Go - MixedCaps](https://go.dev/doc/effective_go#mixed-caps)

| Example | Private | Public |
|:--------:|:-------:|:------:|
| [make_request](https://github.com/BlazingFire007/gurl/blob/main/request.go#L19) | makeRequest | MakeRequest |
| [handle_post](https://github.com/BlazingFire007/gurl/blob/main/request.go#L69) | handlePost | HandlePost |
| [to_file](https://github.com/BlazingFire007/gurl/blob/main/request.go#L91) | toFile | ToFile |
| [parse_args](https://github.com/BlazingFire007/gurl/blob/main/args.go#L26) | parseArgs | ParseArgs |

**Comment by BlazingFire007** [comment]
Thank you! Currently doing a big refactor. Will be sure to include these changes :)
